### ISSUE TITLE
lit_corridor causes explored room tiles to be erroneously displayed as lit

### ISSUE THREAD

**Issue by ToxicFrog** [moon-chilled/slashem9#4]
It looks like in `src/options.c`, `S_darkroom` gets mapped to `S_room` if `lit_corridor` is set. However, there's no visual distinction between "lit room" and "unlit room" once that happens; I would have expected unlit rooms to be dimmed like unlit halls.

This may turn out to be a problem with my tty, but even if it is I'm documenting this here in the hopes that other people with the same problem find it useful.

First, a rundown the glyphs in question:
```
 unlit hall ░ Ux2591 LIGHT SHADE   color 7 plain
   lit hall ▒ Ux2592 MEDIUM SHADE  foreground plain
unlit floor · Ux00B7 MIDDLE DOT    color 7 plain
  lit floor · Ux00B7 MIDDLE DOT    foreground plain
```

Note that "color7" is nominally white; usually 7 plain is light grey and 7 bright is white.

If "plain white" and "plain foreground" are the same colour -- which they are in konsole with the "linux terminal" colour scheme, and several others -- there's no visual distinction between lit and unlit floors. This isn't a problem in vanilla (or wasn't last time I played it) because `lit_corridor` only affected corridors, not rooms, but since it affects both here, it results in no visual distinction between lit and unlit room tiles.

As a quick hack to fix this I've patched `src/drawing.c` to replace the entry for `S_darkroom` (which is mislabeled as `S_stone`) with the same `░` that unlit corridors use in both `utf8_graphics` and `utf8compat_graphics`, and deleting the code in `options.c` that does the remapping. It doesn't really look good but it is at least visually distinctive.

**Comment by moon-chilled** [comment]
Oh, I see; I didn't notice this because it seems to affect just the curses interface.

Probably it should set A_BOLD for colours >8.

**Comment by moon-chilled** [comment]
Fixed.
