### ISSUE TITLE
Build fails at src/readline.o

### ISSUE THREAD

**Issue by weirdvic** [moon-chilled/slashem9#8]
Hello I'm trying to build in a Docker container but the `make install` process fails with the error:
`make: *** No rule to make target 'src/readline.o', needed by 'src/slashem9'.  Stop.`
It looks like file `src/readline.c` is absent from the repository

Steps to reproduce in an alpine container:
1. run a container: `docker run --rm -it alpine`
2. install dependencies: `apk --no-cache add byacc curl flex gc-dev gcc git groff linux-headers make musl-dev ncurses-dev util-linux`
3. make symlink for libncurses: `ln -s libncurses.so /usr/lib/libtinfo.so`
4. clone the repository: `git clone https://github.com/moon-chilled/slashem9.git && cd slashem9`
5. run `make install`

**Comment by moon-chilled** [comment]
Oops, forgot to check those in, thanks.  Note the code is in a somewhat unstable state right now; I started messing with the input code, but haven't finished messing with it, so some things might not work.
